Repository ihmeuw/vivarium_research, pull requests merged in 2021-09, with the labels that each got.

#620 [data] maternal anemia intervention
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/intervention_models/maternal_anemia_intervention/index.rst
Labels: Vivarium modeling strategy

#627 Wasting treatment assumptions from slack discussion
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: Vivarium modeling strategy, CIFF_project

#625 ITN coverage among malarious areas update
  docs/source/intervention_models/insecticide_treated_nets/index.rst
Labels: update, CIFF_project

#628 Wasting treatment implementation proposal
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: CIFF_project

#629 Clarify alternative scenario coverage intentions
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: CIFF_project

#631 Add note of other interventions not considered for CIFF project
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: research background, CIFF_project

#630 Wasting treatment verification criteria
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: CIFF_project

#641 Roll back sphinx-rtd-theme
  ihmehomesnicolyvivarium_researchdocssourceintervention_modelslipid_based_nutrient_supplementsindex.rst
  requirements.txt
Labels: infrastructure

#638 CIFF SAM intervention timing
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: documentation clean up, CIFF_project

#635 Lognormal parameter uncertainty for SQLNS effect sizes & SAM K parameter
  docs/source/intervention_models/lipid_based_nutrient_supplements/index.rst
  docs/source/intervention_models/wasting_treatment/index.rst
  docs/source/model_design/concept_model/statistical_distributions_uncertainty/index.rst
Labels: Vivarium modeling strategy, update, meta modeling strategy, CIFF_project

#642 Wasting treatment documentation clean up
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: research background, documentation clean up, CIFF_project

#643 fix labeling typos for wasting treatment efficacy
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: update, SE review required, CIFF_project, data

#647 Maternal BMI risk exposure
  docs/source/gbd2019_models/risk_exposures/maternal_bmi/index.rst
  docs/source/intervention_models/maternal_supplementation/index.rst
Labels: Vivarium modeling strategy, CIFF_project

#644 Maternal supplementation intervention: change baseline coverage to any iron, link x-factor
  docs/source/intervention_models/maternal_supplementation/coverage_decision_tree.svg
  docs/source/intervention_models/maternal_supplementation/index.rst
Labels: update, documentation clean up, CIFF_project

#653 maternal BMI and birthweight association
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
  docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_birthweight/index.rst
Labels: Vivarium modeling strategy, CIFF_project

#654 CIFF reformat model build versions to table
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: documentation clean up, CIFF_project

#645 Exclude infants less than six months from wasting treatment model
  docs/source/intervention_models/wasting_treatment/index.rst
Labels: SE review required, documentation clean up, CIFF_project

#652 make page specific to bw and wasting, update to reflect six month age
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/bw wasting correlation lit search.xlsx
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/bw_laz_correlation_plot.PNG
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/bw_waz_correlation_plot.PNG
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/bw_wlz_correlation_plot.PNG
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/child_growth_birthweight_correlations.xlsx
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/dag_framework.png
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/index.rst
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/wasting_exposure_dist.drawio
  docs/source/gbd2019_models/risk_risk_correlation/birthweight_wasting/wasting_exposure_dist.svg
Labels: documentation clean up, CIFF_project

#648 Add maternal BMI risk exposure links to CIFF concept model doc
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: update, SE review required, documentation clean up, CIFF_project

#646 Exclude infants <6 months from wasting exposure transitions
  docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
Labels: SE review required, CIFF_project

#655 CIFF concept model update
  docs/source/concept_models/vivarium_ciff_sam/am_concept_model_diagram.svg
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Labels: documentation clean up, CIFF_project
