Repository ihmeuw/vivarium_research, pull requests merged in 2022-10, with the labels that each got.

#998 Wasting model baseline scenario run time update
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: update, SE review required, CIFF_project

#1002 Note on wasting transition truncated normal distribution
  docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
Labels: documentation clean up, CIFF_project

#1001 Record takeaways from China V&V
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Labels: MM_project

#1000 Clarify how adherence and treatments interact at initialization
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: SE review required, CVD_project

#999 Adding census observer information
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#996 IV iron wave 2 status update
  docs/source/concept_models/vivarium_iv_iron/concept_model.rst
Labels: iv_iron_project

#995 International immigration
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/household_moves_puma_distribution.csv
  docs/source/concept_models/vivarium_census_synthdata/non_reference_person_moves_puma_distribution.csv
Labels: PRL_project

#1003 Handle edge case for PUMA matching
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1005 Fix typo in SQ-LNS scale-up parameter
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: documentation clean up, CIFF_project

#1004 Adding an observer for household surveys
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1006 Diarrheal diseases cause model updates
  docs/source/gbd2019_models/causes/diarrheal_diseases/index.rst
  docs/source/gbd2019_models/causes/lower_respiratory_infections/index.rst
Labels: Vivarium modeling strategy, update, documentation clean up, iv_iron_project

#1007 Zinc supplementation overview and modeling notes
  docs/source/intervention_models/zinc_supplementation/index.rst
Labels: documentation clean up, CIFF_project

#1008 Re-revise PUMA edge case handling
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1009 CIFF phase I doc cleanup
  docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
  docs/source/gbd2019_models/risk_effects/diarrheal_diseases/index.rst
Labels: documentation clean up, CIFF_project, verification and validation tracking

#1012 Postpartum depression cause model
  docs/source/gbd2019_models/causes/postpartum_depression/cause_model.svg
  docs/source/gbd2019_models/causes/postpartum_depression/index.rst
Labels: Vivarium modeling strategy, MNCH_project, iv_iron_project

#1010 Discussion of comorbid maternal disorders
  docs/source/gbd2019_models/causes/maternal_disorders/index.rst
  docs/source/other_models/pregnancy/index.rst
Labels: iv_iron_project

#1013 Update readme with reviewer requesting protocol
  README.rst
Labels: SE review required, meta modeling strategy

#1019 Adding matching within names
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1015 Adding CPS observer
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1017 Correct issue with GQ person weights in migration
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1022 Wasting paper sim stratification updates and clarification
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: documentation clean up, wasting_paper

#1024 Changing multiplier to 1 for clarity
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: documentation clean up, CVD_project

#1018 Creating BMI risk effects section
  docs/source/gbd2019_models/risk_effects/bmi/heart_failure_MF.csv
  docs/source/gbd2019_models/risk_effects/bmi/index.rst
Labels: CVD_project

#1026 Wasting paper model 1 V&V tracking
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: verification and validation tracking, wasting_paper

#1016 Generalize ACS sampling perturbation
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/household_moves_puma_distribution.csv
  docs/source/concept_models/vivarium_census_synthdata/non_reference_person_moves_puma_distribution.csv
Labels: PRL_project

#1025 Clarification on missed appointments and screening
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: documentation clean up, CVD_project

#1021 Emigration
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/group_quarters_person_emigration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/household_emigration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/non_reference_person_emigration_rates.csv
Labels: PRL_project

#1011 Adding tax observer
  docs/source/concept_models/vivarium_census_synthdata/1044_example.PNG
  docs/source/concept_models/vivarium_census_synthdata/1044_example.svg
  docs/source/concept_models/vivarium_census_synthdata/W2_example.PNG
  docs/source/concept_models/vivarium_census_synthdata/W2_example.svg
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1020 Updating matching names
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1023 Adding parents/guardians on initialization
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1032 wasting paper model 2.0 v and v
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: SE review required, verification and validation tracking, wasting_paper

#1030 Mainly Outputs Table and Other Small Edits
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: documentation clean up, CVD_project

#1033 Adding SSA observer
  docs/source/concept_models/vivarium_census_synthdata/SSA_example.png
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1031 Handle deaths of reference people
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/reference_person_update_relationship_mapping.csv
  docs/source/concept_models/vivarium_census_synthdata/reference_person_update_relationship_mapping.xlsx
Labels: SE review required, PRL_project

#1028 Standard vivarium results formatting guide
  docs/source/model_design/concept_model/standard_results_formats/index.rst
Labels: SE review required, meta modeling strategy

#1029 Correct RST syntax in README to work with GitHub's rendering
  README.rst
Labels: documentation clean up
