Repository ihmeuw/vivarium_research, pull requests merged in 2022-11, with the labels that each got.

#1038 Updating LDL values and clarifying language
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: CVD_project

#1037 Link to engineering ticket creation instructions
  README.rst
Labels: meta modeling strategy, documentation clean up

#1034 Defining observer elements that are parameterizable
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/survey_example.png
Labels: PRL_project

#1040 Updating the Outreach Intervention
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/intervention_models/crm_mgmt/vivarium_outreach.rst
Labels: SE review required, CVD_project

#1043 Update wasting relapse literature and effect values
  docs/source/gbd2019_models/risk_effects/x_factor/index.rst
Labels: research background, update, wasting_paper

#1044 Adding Current V&V Status for Models 5 and 6
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: verification and validation tracking, CVD_project

#1042 model 3.0 V&V and associated updates
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: update, SE review required, verification and validation tracking, wasting_paper

#1048 Wasting concept model updates from RT/SE check-in
  docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: SE review required, wasting_paper

#1041 Clarifying dependents in taxes with the new guardian information
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/minors_gen_pop.drawio.svg
Labels: SE review required, PRL_project

#1046 Updating SBP and LDL-C ramps to allow non-adherent folks on interventions
  docs/source/concept_models/vivarium_us_cvd/ldl_ramp_all.svg
  docs/source/concept_models/vivarium_us_cvd/sbp_ramp_all.svg
  docs/source/intervention_models/crm_mgmt/vivarium_outreach.rst
Labels: SE review required, CVD_project

#1049 Document SSN percentages and initialization, persistent ITIN
  docs/source/concept_models/vivarium_census_synthdata/1044_example.PNG
  docs/source/concept_models/vivarium_census_synthdata/1044_example.png
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1052 Custom parameterized draw feature overview
  docs/source/model_design/vivarium_features/custom_parameterized_draw/index.rst
Labels: meta modeling strategy

#1047 Creating a WIC Observer
  docs/source/concept_models/vivarium_census_synthdata/WIC_example.png
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1039 Re-document domestic migration
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/gq_person_move_relationship_proportions.csv
  docs/source/concept_models/vivarium_census_synthdata/household_domestic_migration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/individual_domestic_migration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/non_reference_person_move_relationship_proportions.csv
Labels: SE review required, PRL_project

#1054 Requested guardian clarifications
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1053 Finalize input files for domestic migration
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/concept_models/vivarium_census_synthdata/gq_person_move_relationship_proportions.csv
  docs/source/concept_models/vivarium_census_synthdata/household_domestic_migration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/individual_domestic_migration_rates.csv
  docs/source/concept_models/vivarium_census_synthdata/non_reference_person_move_relationship_proportions.csv
Labels: PRL_project

#1058 Update values and show work for variance split
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1061 Heart failure updates
  docs/source/gbd2019_models/causes/heart_failure/index.rst
  docs/source/gbd2019_models/causes/ihd/cause_model_ami_and_hf.svg
  docs/source/gbd2019_models/causes/ihd/index.rst
Labels: SE review required, CVD_project

#1051 Document employment as currently implemented
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1063 Updates from V&V
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Labels: verification and validation tracking, CVD_project
