Repository ihmeuw/vivarium_research, pull requests merged in 2022-06, with the labels that each got.

#885 child model 4 v and v
  docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project

#887 Updated BW shift CIs due to joint BMI and hemoglobin category
  docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_hgb_birthweight/index.rst
  docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_hgb_birthweight/md calculations.xlsx
Labels: update, data, iv_iron_project

#889 First draft of documenting treatment prediction
  docs/source/intervention_models/multiple_myeloma_treatment/hex_to_binary.py
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/verify_model_probabilities.py
Labels: MM_project

#891 add links to non-age-specific values
  docs/source/gbd2019_models/risk_exposures/maternal_bmi_hgb/index.rst
  docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_hgb_birthweight/index.rst
Labels: data, iv_iron_project

#888 intervention effects validation table
  docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project

#882 add list of validation conclusions from model 8
  docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project

#892 Python version 3.6->3.8 in environment setup
  README.rst
Labels: documentation clean up

#884 update output table shell
  docs/source/concept_models/vivarium_iv_iron/maternal_model/output_table.csv
Labels: iv_iron_project

#890 Document multiple myeloma treatment effects with placeholder values
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/mortality_hrs.csv
  docs/source/intervention_models/multiple_myeloma_treatment/relapse_hrs.csv
Labels: MM_project

#895 Document treatment and survival output format
  docs/source/concept_models/vivarium_csu_multiple_myeloma/concept_model.rst
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Labels: MM_project

#894 Document naive MM treatment prediction models
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/verify_model_probabilities.py
Labels: MM_project

#901 Document risk effects for Phase 2
  docs/source/gbd2019_models/risk_effects/mm_risk_effects/index.rst
  docs/source/gbd2019_models/risk_exposures/mm_risk_exposures/index.rst
Labels: MM_project

#897 Document V&V strategy for model 1
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
Labels: MM_project

#900 Multiple myeloma cause model updates
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
  docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma_2/cancer_model.rst
  docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma_2/cause_model_diagram.svg
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/mortality_hrs.csv
  docs/source/intervention_models/multiple_myeloma_treatment/relapse_hrs.csv
Labels: MM_project

#903 Model 0 V&V log round 1
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Labels: MM_project

#904 Update parts of Phase 2 concept model that differ from Phase 1
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model_diagram.svg
Labels: MM_project

#906 Add timestep-dependent input data
  docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma_2/cancer_model.rst
Labels: MM_project
