Repository ihmeuw/vivarium_research, pull requests merged in 2022-12, with the labels that each got.

#1070 College GQ Guardians Updates
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1066 Document mailing address
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1064 Update proportions of special employers
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1068 Correct physical address to work in the GQ case
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1069 Small updates from combining IHD and HF and removing angina
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/gbd2019_models/risk_effects/bmi/index.rst
  docs/source/gbd2019_models/risk_effects/ldl/index.rst
  docs/source/gbd2019_models/risk_effects/sbp/index.rst
Labels: documentation clean up, CVD_project

#1067 Adjusting polypill intervention
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/concept_models/vivarium_us_cvd/sbp_ramp_all.svg
  docs/source/intervention_models/crm_mgmt/vivarium_polypill.rst
Labels: CVD_project

#1071 Use Abie's mailing address wording correction
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1059 Restructure risk factors page(s)
  docs/source/model_design/vivarium_model_components/impairments/index.rst
  docs/source/model_design/vivarium_model_components/index.rst
  docs/source/model_design/vivarium_model_components/risk_effects/index.rst
  docs/source/model_design/vivarium_model_components/risk_exposure/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/population_attributable_fraction/PAF_intuitive_diagram.svg
  docs/source/model_design/vivarium_model_components/risk_factors/population_attributable_fraction/darrow_confounding_figures.jpg
  docs/source/model_design/vivarium_model_components/risk_factors/population_attributable_fraction/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_attributable_causes/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_10_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_13_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_29_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_30_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_5_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_9_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/Risk-Risk Correlation.pptx
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/gaussian_copulae.jpg
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/rate_dotplot.jpg
  docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/mediation_example_bmi.svg
  docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/prevalence_diagram.svg
  docs/source/model_design/vivarium_model_components/risk_factors/risk_exposure/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_mediation/index.rst
Labels: documentation clean up

#1075 Missing census files
  docs/source/models/concept_models/vivarium_census_synthdata/1044_example.png
  docs/source/models/concept_models/vivarium_census_synthdata/1044_example.svg
  docs/source/models/concept_models/vivarium_census_synthdata/SSA_example.png
  docs/source/models/concept_models/vivarium_census_synthdata/W2_example.PNG
  docs/source/models/concept_models/vivarium_census_synthdata/W2_example.svg
  docs/source/models/concept_models/vivarium_census_synthdata/WIC_example.png
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/models/concept_models/vivarium_census_synthdata/group_quarters_person_emigration_rates.csv
  docs/source/models/concept_models/vivarium_census_synthdata/household_emigration_rates.csv
  docs/source/models/concept_models/vivarium_census_synthdata/minors_gen_pop.drawio.svg
  docs/source/models/concept_models/vivarium_census_synthdata/non_reference_person_emigration_rates.csv
  docs/source/models/concept_models/vivarium_census_synthdata/puma_to_zip.csv
  docs/source/models/concept_models/vivarium_census_synthdata/reference_person_update_relationship_mapping.csv
  docs/source/models/concept_models/vivarium_census_synthdata/reference_person_update_relationship_mapping.xlsx
  docs/source/models/concept_models/vivarium_census_synthdata/survey_example.png
Labels: documentation clean up

#1065 Adding FPG Risk Effects Page
  docs/source/models/risk_effects/fpg/index.rst
Labels: CVD_project

#1074 Splitting general epi into two pages
  docs/source/model_design/general_reference_material/casual_diagrams/acyclic_dags.svg
  docs/source/model_design/general_reference_material/casual_diagrams/backdoor_path_dag.svg
  docs/source/model_design/general_reference_material/casual_diagrams/basic_int_diagram.svg
  docs/source/model_design/general_reference_material/casual_diagrams/closed_backdoor_paths.svg
  docs/source/model_design/general_reference_material/casual_diagrams/collider_dag.svg
  docs/source/model_design/general_reference_material/casual_diagrams/confounding_triangle.svg
  docs/source/model_design/general_reference_material/casual_diagrams/dashed_association.svg
  docs/source/model_design/general_reference_material/casual_diagrams/directional_dag.svg
  docs/source/model_design/general_reference_material/casual_diagrams/effect_mod_arrow_diagram.svg
  docs/source/model_design/general_reference_material/casual_diagrams/index.rst
  docs/source/model_design/general_reference_material/casual_diagrams/medication_example.svg
  docs/source/model_design/general_reference_material/casual_diagrams/open_backdoor_paths.svg
  docs/source/model_design/general_reference_material/casual_diagrams/paths_closed_by_colliders.svg
  docs/source/model_design/general_reference_material/casual_diagrams/risk_factors_mediation_diagram.svg
  docs/source/model_design/general_reference_material/casual_diagrams/risk_factors_mediation_example.svg
  docs/source/model_design/general_reference_material/casual_diagrams/smoking_intermediate_example (2).svg
  docs/source/model_design/general_reference_material/casual_diagrams/smoking_intermediate_example.svg
  docs/source/model_design/general_reference_material/casual_diagrams/smoking_intervention_example.svg
  docs/source/model_design/general_reference_material/casual_diagrams/smoking_triangle.svg
  docs/source/model_design/general_reference_material/casual_diagrams/unknown_var_association.svg
  docs/source/model_design/general_reference_material/casual_diagrams/with_em_illustration.jpg
  docs/source/model_design/general_reference_material/casual_diagrams/with_em_illustration.svg
  docs/source/model_design/general_reference_material/casual_diagrams/without_em_illustration.jpg
  docs/source/model_design/general_reference_material/casual_diagrams/without_em_illustration.svg
  docs/source/model_design/general_reference_material/finding_evaluating_studies/case_control_design_visual.svg
  docs/source/model_design/general_reference_material/finding_evaluating_studies/index.rst
  docs/source/model_design/general_reference_material/finding_evaluating_studies/iron_meta.png
Labels: documentation clean up

#1076 Wasting model 3.0.1 v and v updates
  docs/source/models/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: verification and validation tracking, wasting_paper

#1078 Changing eligibility for polypill slightly
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/models/intervention_models/crm_mgmt/vivarium_polypill.rst
Labels: SE review required, CVD_project

#1077 Adding upper BMI limit
  docs/source/models/risk_exposures/bmi/index.rst
Labels: SE review required, CVD_project

#1072 Updates to Heart Failure
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/cause_model_ami_and_hf.svg
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/index.rst
Labels: SE review required, CVD_project

#1060 Cause model for other causes with YLDs
  docs/source/models/causes/other_causes/figure.drawio
  docs/source/models/causes/other_causes/figure.svg
  docs/source/models/causes/other_causes/index.rst
Labels: SE review required, meta modeling strategy

#1082 Change maximum age in perturbation
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1081 Restore up-to-date version of PRL concept model
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1084 Add V&V strategy for migration components
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1083 Clarify strategy for international immigration
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1080 Update wasting population size from 260,000 to 250,000
  docs/source/models/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: documentation clean up, wasting_paper

#1085 Document processing of address data
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1086 Fixing unit error in LDL-C initialization code
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Labels: SE review required, CVD_project

#1087 Make PRL subheadings italic
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1092 Requiring high ASCVD risk to move up LDL-C med ladder
  docs/source/models/concept_models/vivarium_us_cvd/ldl_ramp_all.svg
Labels: CVD_project

#1091 BMI Mediation for CVD
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/index.rst
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/models/risk_effects/bmi/heart_failure_MF.csv
  docs/source/models/risk_effects/bmi/index.rst
Labels: CVD_project

#1089 Observer updates for addresses, sampling plan, and adding data needed for noise functions
  docs/source/models/concept_models/vivarium_census_synthdata/WIC_example.png
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
  docs/source/models/concept_models/vivarium_census_synthdata/survey_example.png
Labels: SE review required, PRL_project

#1093 Defining the format for DOB
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1094 Assigning 1 middle name for all
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1096 Edge case for guardians
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1095 Adding Omissions
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1097 SQ-LNS updates from collaborators
  docs/source/models/intervention_models/lipid_based_nutrient_supplements/index.rst
  docs/source/models/intervention_models/lipid_based_nutrient_supplements/viviarium_strategy_stunting.svg
Labels: update, SE review required, wasting_paper

#1100 Wasting paper concept model update for SQ-LNS model
  docs/source/models/concept_models/vivarium_ciff_sam_2/concept_model.rst
Labels: update, SE review required, wasting_paper

#1101 Updates to risk factor modeling page
  docs/source/model_design/vivarium_model_components/risk_factors/index.rst
Labels: meta modeling strategy, documentation clean up

#1102 Risk exposure page doc cleanup
  docs/source/model_design/vivarium_model_components/risk_factors/risk_exposure/index.rst
Labels: meta modeling strategy, documentation clean up

#1103 First pass at risk effects page review
  docs/source/model_design/general_reference_material/measures_of_risk/index.rst
  docs/source/model_design/general_reference_material/measures_of_risk/prevalence_diagram.svg
  docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst
Labels: meta modeling strategy, documentation clean up

#1105 Clarify income documentation
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1088 Defining Column Noise
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1106 Order of Noise Functions
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#972 DOC: change term-of-art to simulated data
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1027 ENH: add detail about unique names for employers
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project
