Repository ihmeuw/vivarium_research, pull requests merged in 2022-07, with the labels that each got.

#910 Document MM Phase 2 scenarios
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
  docs/source/intervention_models/multiple_myeloma_treatment/dara_coverage_from_flatiron.csv
  docs/source/intervention_models/multiple_myeloma_treatment/dara_coverage_plot.png
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/target_dara_coverage.csv
  docs/source/intervention_models/multiple_myeloma_treatment/target_isa_coverage.csv
Labels: MM_project

#911 testing changes and adding a todo for 2020 measles updates
  docs/source/gbd2020_models/causes/cause_model_template.rst
  docs/source/gbd2020_models/causes/index.rst
  docs/source/gbd2020_models/causes/measles/index.rst
  docs/source/gbd2020_models/causes/measles/measles_cause_model.svg
  docs/source/gbd2020_models/causes/measles/measles_gbd_hierarchy.svg
Labels: template, CIFF_project

#909 link to maternal V&V notebooks for last few model iterations
  docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project

#912 Adding more todo's and minor updates
  docs/source/gbd2020_models/causes/measles/index.rst
Labels: template, CIFF_project

#917 Correct Dara target coverage file
  docs/source/intervention_models/multiple_myeloma_treatment/target_dara_coverage.csv
Labels: MM_project

#915 Measles 2020 - adding in explanation on age group changes to measles doc from GBD team
  docs/source/gbd2020_models/causes/measles/index.rst
Labels: research background, CIFF_project

#916 Fix retreatment issues in Model 3 scenarios
  docs/source/intervention_models/multiple_myeloma_treatment/dara_coverage_from_flatiron.csv
  docs/source/intervention_models/multiple_myeloma_treatment/hex_to_binary.py
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/target_dara_coverage.csv
  docs/source/intervention_models/multiple_myeloma_treatment/verify_model_probabilities.py
Labels: MM_project

#919 Update treatment HRs, document calculation method
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/mortality_hrs.csv
  docs/source/intervention_models/multiple_myeloma_treatment/relapse_hrs.csv
Labels: MM_project

#920 Update treatment assignment models
  docs/source/intervention_models/multiple_myeloma_treatment/dara_coverage_from_flatiron.csv
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/verify_model_probabilities.py
Labels: MM_project

#923 Document best-guess Dara projections
  docs/source/intervention_models/multiple_myeloma_treatment/dara_coverage_plot.png
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
  docs/source/intervention_models/multiple_myeloma_treatment/target_dara_coverage.csv
Labels: MM_project

#925 Extrapolate Isa target coverage to full timespan
  docs/source/intervention_models/multiple_myeloma_treatment/target_isa_coverage.csv
Labels: MM_project

#924 DOC: more details on DOB noise model for PRL synth data
  docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#929 Cleaning and reorganizing concept model page for CVD
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/concept_models/vivarium_us_cvd/decision_tree_emergency.html
  docs/source/concept_models/vivarium_us_cvd/decision_tree_followup.svg
  docs/source/concept_models/vivarium_us_cvd/decision_tree_none.svg
  docs/source/concept_models/vivarium_us_cvd/decision_tree_screening.svg
  docs/source/concept_models/vivarium_us_cvd/sbp_ramp_followup.svg
  docs/source/concept_models/vivarium_us_cvd/sbp_ramp_initial.svg
  docs/source/intervention_models/crm_mgmt/affected_outcomes.rst
  docs/source/intervention_models/crm_mgmt/initialization.rst
  docs/source/intervention_models/crm_mgmt/tx.rst
  docs/source/intervention_models/crm_mgmt/visit.rst
  docs/source/intervention_models/crm_mgmt/vivarium_lifestyle.rst
  docs/source/intervention_models/crm_mgmt/vivarium_outreach.rst
  docs/source/intervention_models/crm_mgmt/vivarium_polypill.rst
Labels: template, documentation clean up, CVD_project

#926 Model 2 V&V summary
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Labels: MM_project

#928 Update pickle files and postprocessing rules
  .gitignore
  docs/source/intervention_models/multiple_myeloma_treatment/index.rst
Labels: MM_project

#930 initial changes to outreach intervention
  docs/source/intervention_models/crm_mgmt/vivarium_outreach.rst
Labels: template, CVD_project

#922 V and V notes for model 0 age stratified and model 1
  docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Labels: MM_project, verification and validation tracking

#931 Adding diagrams and descriptions for healthcare interactions and begi…
  docs/source/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/concept_models/vivarium_us_cvd/concept_model_v3.svg
  docs/source/concept_models/vivarium_us_cvd/decision_tree_emergency.html
  docs/source/concept_models/vivarium_us_cvd/decision_tree_emergency.svg
  docs/source/concept_models/vivarium_us_cvd/sbp_ramp_initial.svg
Labels: research background, documentation clean up, CVD_project

#932 IV iron child model V&V table update
  docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project

#933 IV iron 3 day timestep V&V notes
  docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst
Labels: verification and validation tracking, iv_iron_project
