Repository ihmeuw/vivarium_research, pull requests merged in 2023-01, with the labels that each got.

#1098 Clarify that individual move types are exclusive
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1108 Correct probit to standard normal CDF
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1107 Clarify limitation of employment change on move
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1112 Removing old heart failure docs
  docs/source/models/causes/heart_failure/cause_model_hf_residual.svg
  docs/source/models/causes/heart_failure/index.rst
Labels: SE review required, documentation clean up, CVD_project

#1110 Creating CVD risk correlation page
  docs/source/models/risk_correlation/sbp_ldlc_fpg_bmi/correlation.csv
  docs/source/models/risk_correlation/sbp_ldlc_fpg_bmi/correlation_graphs.png
  docs/source/models/risk_correlation/sbp_ldlc_fpg_bmi/index.rst
Labels: CVD_project

#1111 Excluding BMI standard deviation outliers
  docs/source/models/risk_exposures/bmi/index.rst
Labels: CVD_project

#1114 Updates from wasting paper model 3.1
  docs/source/models/concept_models/vivarium_ciff_sam_2/concept_model.rst
  docs/source/models/intervention_models/lipid_based_nutrient_supplements/index.rst
Labels: update, verification and validation tracking, wasting_paper

#1117 Replace use of "parent_ids" with description
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1119 Creating HF PAFs for unmediated and uncorrelated runs
  docs/source/models/risk_effects/bmi/index.rst
  docs/source/models/risk_effects/sbp/index.rst
Labels: CVD_project

#1090 Do a first pass of improvement on risk correlation
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_10_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_13_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_29_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_30_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_5_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/2020_02_11a_correlation_and_paf_files/2020_02_11a_correlation_and_paf_9_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/Why_is_getting_the_paf_right_.pdf
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/correlated_exposures_sim.R
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/risk_mediation/Risk-Risk Correlation.pptx
  docs/source/model_design/vivarium_model_components/risk_factors/risk_mediation/index.rst
  docs/source/models/concept_models/vivarium_ciff_sam/concept_model.rst
  docs/source/models/risk_correlation/birthweight_stunting/index.rst
  docs/source/models/risk_correlation/birthweight_wasting/index.rst
Labels: Vivarium modeling strategy

#1109 Emigration revisions
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1116 Data formatting specifications
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1118 Use a single state and PUMA per GQ type
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1121 Switch from ssh to https in contributing instructions
  README.rst
Labels: documentation clean up

#1122 Typo in FPG doc
  docs/source/models/risk_effects/fpg/index.rst
Labels: documentation clean up, CVD_project

#1120 Removing dependents tracking from W2/1099
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1123 Clean up last name, include race/ethnicity logic
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project
