Repository ihmeuw/vivarium_research, pull requests merged in 2023-04, with the labels that each got.

#1166 Nit: consistent format for ZIP in noise table
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1167 Adjusting FPG values on lifestyle ramp to correct units
  docs/source/models/concept_models/vivarium_us_cvd/lifestyle_ramp.svg
Labels: documentation clean up, CVD_project

#1168 Updating age of cohort at start due to error
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Labels: SE review required, CVD_project

#1170 Describe date subsetting in each observer
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1169 Adjusting LDL treatment ramp for older adults
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/models/concept_models/vivarium_us_cvd/ldl_ramp_all.svg
Labels: SE review required, CVD_project

#1148 Computer resources new page
  docs/source/index.rst
  docs/source/onboarding_resources/computing/index.rst
  docs/source/onboarding_resources/computing/putty_1.png
  docs/source/onboarding_resources/computing/putty_2.png
  docs/source/onboarding_resources/computing/putty_3.png
  docs/source/onboarding_resources/contributing/index.rst
  docs/source/onboarding_resources/index.rst
Labels: Vivarium modeling strategy, meta modeling strategy

#1174 Specify order of columns in pseudopeople output
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1171 Nutrition optimization simulation landing page
  docs/source/models/concept_models/vivarium_nutrition_optimization/concept_model.rst
Labels: template, nutrition_optimization

#1173 Rename wasting paper concept model
  docs/source/models/concept_models/vivarium_wasting_paper/DAG_acute_malnutrition.drawio
  docs/source/models/concept_models/vivarium_wasting_paper/DAG_acute_malnutrition.svg
  docs/source/models/concept_models/vivarium_wasting_paper/SAM_compartmental_diagram
  docs/source/models/concept_models/vivarium_wasting_paper/am_concept_model_diagram.svg
  docs/source/models/concept_models/vivarium_wasting_paper/concept_model.rst
  docs/source/models/concept_models/vivarium_wasting_paper/correlation_structure.svg
  docs/source/models/concept_models/vivarium_wasting_paper/final_outcomes_output_shell.csv
  docs/source/models/concept_models/vivarium_wasting_paper/simulation_output_table.csv
  docs/source/models/concept_models/vivarium_wasting_paper/stratification_details_for_test_run.png
Labels: documentation clean up

#1175 Run request of wasting paper for nutrition optimization tests
  docs/source/models/concept_models/vivarium_wasting_paper/concept_model.rst
Labels: wasting_paper, nutrition_optimization

#1176 CVD Recent V&V Updates and Model Runs
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Labels: CVD_project

#1179 PRL: Clean up column noise table
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1178 Cause restrictions and typo fix in maternal disorders page
  docs/source/model_design/vivarium_model_components/causes/index.rst
  docs/source/models/causes/maternal_disorders/index.rst
Labels: Vivarium modeling strategy, documentation clean up

#1182 Adding Environment and Package Information to Computing Resources
  docs/source/onboarding_resources/computing/index.rst
Labels: meta modeling strategy

#1187 Updating IHD cause model to fix probability > 1 failures
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/cause_model_ami_and_hf.svg
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/index.rst
  docs/source/models/risk_exposures/bmi/index.rst
  docs/source/models/risk_exposures/fpg/index.rst
  docs/source/models/risk_exposures/ldl/gbd_2019/index.rst
  docs/source/models/risk_exposures/sbp/index.rst
Labels: SE review required, CVD_project
