Repository ihmeuw/vivarium_research, pull requests merged in 2023-02, with the labels that each got.

#1125 Updating BMI and FPG V&V Results
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Labels: verification and validation tracking, CVD_project

#1127 Adding FPG bounds
  docs/source/models/risk_exposures/fpg/index.rst
Labels: CVD_project

#1126 Adding lifestyle intervention
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
  docs/source/models/concept_models/vivarium_us_cvd/lifestyle_ramp.svg
  docs/source/models/intervention_models/crm_mgmt/bmi.png
  docs/source/models/intervention_models/crm_mgmt/fpg.png
  docs/source/models/intervention_models/crm_mgmt/sbp.png
  docs/source/models/intervention_models/crm_mgmt/vivarium_lifestyle.rst
Labels: CVD_project

#1128 Clarify noise order, add OCR and typographic noise
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1113 Risk correlation bias quantification
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/bias_quantification.ipynb
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/correlated_risks_1.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/correlated_risks_2.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/correlated_risks_3.png
  docs/source/model_design/vivarium_model_components/risk_factors/risk_correlation/index.rst
Labels: meta modeling strategy

#1131 FPG testing at initialization and adding HF sequelae
  docs/source/models/causes/ischemic_heart_disease/gbd_2019/index.rst
  docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Labels: SE review required, CVD_project

#1129 Adding pop size and some adjustments to PAF calculations
  docs/source/models/risk_effects/bmi/index.rst
Labels: SE review required, CVD_project

#1133 Updating lifestyle intervention ramp
  docs/source/models/concept_models/vivarium_us_cvd/lifestyle_ramp.svg
Labels: SE review required, CVD_project

#1135 Reduce standard deviation of age perturbation
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1124 Clean up PRL introduction, fertility docs
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: documentation clean up, PRL_project

#1134 PRL immigration revisions
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1136 Clean up demographics and ACS-based initialization
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1132 Adding mortality impact definitions to table
  docs/source/model_design/vivarium_model_components/causes/index.rst
Labels: documentation clean up

#1130 Residual confounding background
  docs/source/model_design/vivarium_model_components/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/residual_confounding/diagram.png
  docs/source/model_design/vivarium_model_components/risk_factors/residual_confounding/index.rst
  docs/source/model_design/vivarium_model_components/risk_factors/residual_confounding/rc_diagram.png
Labels: meta modeling strategy

#1137 Switching order of missing data to be after row noise
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1140 Adding mediation to FPG through LDL
  docs/source/models/risk_effects/fpg/index.rst
Labels: CVD_project

#1141 Joint PAFs for CVD
  docs/source/models/risk_correlation/sbp_ldlc_fpg_bmi/index.rst
Labels: CVD_project

#1142 Clarifying reselection of SSN for taxes
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: SE review required, PRL_project

#1143 Noting limitation on SSN sharing in GQ
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1139 Adding transitions definitions to data defs table
  docs/source/model_design/vivarium_model_components/causes/index.rst
Labels: documentation clean up
