Repository ihmeuw/vivarium_research, pull requests merged in 2024-06, with the labels that each got.

#1500 Updating docs from SQ-LNS work
  docs/source/models/intervention_models/lipid_based_nutrient_supplements/index.rst
Labels: MNCH_project

#1502 Updating debugging section from IPython to Jupyter in VS Code
  docs/source/model_design/programming_vivarium/debugging/index.rst
Labels: Vivarium modeling strategy, meta modeling strategy

#1501 Model 14.1 V&V write-up
  docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Labels: MNCH_project, verification and validation tracking

#1503 Model 14.1 V&V Part 2
  docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Labels: MNCH_project, verification and validation tracking

#1505 Model 14.1.1 V&V
  docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Labels: MNCH_project, verification and validation tracking

#1485 Data links for 2021 Ethiopian CGF
  docs/source/models/concept_models/vivarium_nutrition_optimization/concept_model.rst
Labels: data, nutrition_optimization
