Repository ihmeuw/vivarium_research, pull requests merged in 2025-03, with the labels that each got.

#1599 Add alternative PAF derivation to CPAP page
  docs/source/models/intervention_models/neonatal/cpap_intervention.rst
Labels: MNCNH_portfolio

#1598 Revision to neonatal intervention docs
  docs/source/models/intervention_models/neonatal/antibiotics_intervention.rst
  docs/source/models/intervention_models/neonatal/cpap_intervention.rst
Labels: MNCNH_portfolio

#1600 Specify uncertainty on do-not-respond target for fuzzy checking
  docs/source/model_design/vivarium_features/automated_v_and_v/index.rst
  docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Labels: PRL_project

#1602 Unpin Sphinx
  requirements.txt
Labels: infrastructure

#1601 Updates to preterm cause model
  docs/source/models/causes/neonatal/preterm_birth.rst
Labels: MNCNH_portfolio

#1604 GBD 2023 hemoglobin model: create page structure and add templates
  docs/source/models/other_models/hemoglobin_anemia_and_iron_deficiency/hemoglobin/gbd_2021/index.rst
  docs/source/models/other_models/hemoglobin_anemia_and_iron_deficiency/hemoglobin/gbd_2023/index.rst
  docs/source/models/other_models/hemoglobin_anemia_and_iron_deficiency/hemoglobin/index.rst
  docs/source/models/other_models/hemoglobin_anemia_and_iron_deficiency/index.rst
  docs/source/models/risk_effects/hemoglobin/index.rst
  docs/source/models/risk_exposures/hemoglobin/index.rst
Labels: template, MNCNH_portfolio

#1605 Hemoglobin risk exposure document
  docs/source/models/risk_exposures/hemoglobin/index.rst
Labels: MNCNH_portfolio

#1609 Add scenarios section to MNCNH concept model doc
  docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
Labels: MNCNH_portfolio

#1607 Hemoglobin risk effects page
  docs/source/models/risk_effects/hemoglobin/index.rst
  docs/source/models/risk_effects/hemoglobin/maternal_disorders_risk_curve.png
Labels: Vivarium modeling strategy, MNCNH_portfolio

#1610 Document proposed improvement to CRN for CoD assignment
  docs/source/model_design/vivarium_features/cause_of_death_selection/cod_diagram.drawio.svg
  docs/source/model_design/vivarium_features/cause_of_death_selection/cod_issue_diagram.drawio.svg
  docs/source/model_design/vivarium_features/cause_of_death_selection/cod_reservation_diagram.drawio.svg
  docs/source/model_design/vivarium_features/cause_of_death_selection/cod_reservation_overflow_diagram.drawio.svg
  docs/source/model_design/vivarium_features/cause_of_death_selection/cod_solution_diagram.drawio.svg
  docs/source/model_design/vivarium_features/cause_of_death_selection/index.rst
Labels: Vivarium modeling strategy
